name: queryyourpdf
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python=3.11
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
      - gradio
      - python-dotenv
      - langchain
      - langchain-core
      - langchain-text-splitters
      - langchain-openai
      - langchain-chroma
      - langchain-community
      - faiss-cpu
      - chromadb
      - pypdf
      - google-api-core